### ISSUE TITLE
An application with email templates can not start with graphql

### ISSUE THREAD

**Issue by owlet1997** [Haulmont/jmix-graphql#183]
**Environment:**
Jmix version: 1.1.0-SNAPSHOT, 1.0.1
Jmix Studio plugin version: 1.0.1-212
IntelliJ version: IntelliJ IDEA 2021.2 (Ultimate Edition)

**TC:**
1. Create new project
2. Add frontend module 
3. Add email templates add-on 
4. Run app

**AR:**
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'graphQLSchema' defined in class path resource [io/jmix/graphql/GraphQLConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [graphql.schema.GraphQLSchema]: Factory method 'graphQLSchema' threw exception; nested exception is io.jmix.graphql.spqr.SchemaGenerationException: Type name collision: multiple registered additional types are named 'TemplateType'
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658) ~[spring-beans-5.3.8.jar:5.3.8]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638) ~[spring-beans-5.3.8.jar:5.3.8]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1334) ~[spring-beans-5.3.8.jar:5.3.8]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177) ~[spring-beans-5.3.8.jar:5.3.8]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564) ~[spring-beans-5.3.8.jar:5.3.8]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524) ~[spring-beans-5.3.8.jar:5.3.8]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.8.jar:5.3.8]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.8.jar:5.3.8]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.8.jar:5.3.8]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.8.jar:5.3.8]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) ~[spring-beans-5.3.8.jar:5.3.8]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.8.jar:5.3.8]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.8.jar:5.3.8]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.5.2.jar:2.5.2]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) [spring-boot-2.5.2.jar:2.5.2]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434) [spring-boot-2.5.2.jar:2.5.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:338) [spring-boot-2.5.2.jar:2.5.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) [spring-boot-2.5.2.jar:2.5.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332) [spring-boot-2.5.2.jar:2.5.2]
	at com.company.j101.J101Application.main(J101Application.java:25) [main/:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [graphql.schema.GraphQLSchema]: Factory method 'graphQLSchema' threw exception; nested exception is io.jmix.graphql.spqr.SchemaGenerationException: Type name collision: multiple registered additional types are named 'TemplateType'
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.3.8.jar:5.3.8]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-beans-5.3.8.jar:5.3.8]
	... 19 common frames omitted
Caused by: io.jmix.graphql.spqr.SchemaGenerationException: Type name collision: multiple registered additional types are named 'TemplateType'
	at io.jmix.graphql.spqr.BaseSpqrSchemaGenerator.merge(BaseSpqrSchemaGenerator.java:642) ~[jmix-graphql-1.1.0-SNAPSHOT.jar:na]
	at io.jmix.graphql.spqr.BaseSpqrSchemaGenerator.lambda$withAdditionalTypes$18(BaseSpqrSchemaGenerator.java:629) ~[jmix-graphql-1.1.0-SNAPSHOT.jar:na]
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[na:1.8.0_275]
	at io.jmix.graphql.spqr.BaseSpqrSchemaGenerator.withAdditionalTypes(BaseSpqrSchemaGenerator.java:629) ~[jmix-graphql-1.1.0-SNAPSHOT.jar:na]
	at io.jmix.graphql.spqr.BaseSpqrSchemaGenerator.withAdditionalTypes(BaseSpqrSchemaGenerator.java:621) ~[jmix-graphql-1.1.0-SNAPSHOT.jar:na]
	at io.jmix.graphql.GraphQLConfiguration.graphQLSchema(GraphQLConfiguration.java:152) ~[jmix-graphql-1.1.0-SNAPSHOT.jar:na]
	at io.jmix.graphql.GraphQLConfiguration$$EnhancerBySpringCGLIB$$9bee613b.CGLIB$graphQLSchema$0(<generated>) ~[jmix-graphql-1.1.0-SNAPSHOT.jar:na]
	at io.jmix.graphql.GraphQLConfiguration$$EnhancerBySpringCGLIB$$9bee613b$$FastClassBySpringCGLIB$$8d098c26.invoke(<generated>) ~[jmix-graphql-1.1.0-SNAPSHOT.jar:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.3.8.jar:5.3.8]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-5.3.8.jar:5.3.8]
	at io.jmix.graphql.GraphQLConfiguration$$EnhancerBySpringCGLIB$$9bee613b.graphQLSchema(<generated>) ~[jmix-graphql-1.1.0-SNAPSHOT.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_275]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_275]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_275]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_275]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.8.jar:5.3.8]
	... 20 common frames omitted

Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [graphql.schema.GraphQLSchema]: Factory method 'graphQLSchema' threw exception; nested exception is io.jmix.graphql.spqr.SchemaGenerationException: Type name collision: multiple registered additional types are named 'TemplateType'

Caused by: io.jmix.graphql.spqr.SchemaGenerationException: Type name collision: multiple registered additional types are named 'TemplateType'
```

**Comment by dtaimanov** [comment]
Looks like duplicate of Haulmont/jmix-graphql#169
please, check again after that ticket will be fixed

**Comment by owlet1997** [comment]
checked on 1.1.0-SNAPSHOT, fixed
